 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Traceback (most recent call last):
  File "/home/gianni/vanano/app.py", line 1, in <module>
    from flask import Flask, render_template, request, redirect, url_for
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError
  File "/usr/lib/python3/dist-packages/werkzeug/routing/__init__.py", line 123, in <module>
    from .map import Map as Map
  File "/usr/lib/python3/dist-packages/werkzeug/routing/map.py", line 41, in <module>
    class Map:
  File "/usr/lib/python3/dist-packages/werkzeug/routing/map.py", line 96, in Map
    rules: t.Optional[t.Iterable["RuleFactory"]] = None,
                      ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 341, in inner
    return cached(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 1536, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 1536, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)

KeyboardInterrupt
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5050
 * Running on http://192.168.1.34:5050
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 865-899-231
192.168.1.25 - - [27/Feb/2025 17:18:08] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:08] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:11] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:11] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:12] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:12] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:12] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:13] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:13] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:14] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:21] "POST /post HTTP/1.1" 302 -
192.168.1.25 - - [27/Feb/2025 17:18:21] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:21] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:21] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:26] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:26] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:38] "POST /post HTTP/1.1" 302 -
192.168.1.25 - - [27/Feb/2025 17:18:38] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:38] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:38] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:38] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:44] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:18:44] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:44] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:18:44] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:20:01] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:20:01] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:20:01] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:20:01] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:20:07] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:20:08] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:20:08] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:20:08] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:25:17] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:17] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:17] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:17] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:25] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:26] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:26] "GET /favicon.ico HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:25:45] "POST /post HTTP/1.1" 302 -
192.168.1.25 - - [27/Feb/2025 17:25:45] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:45] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:25:45] "GET /static/uploads/index.html HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:25:45] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:25:46] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:26:35] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:26:35] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:26:35] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:26:35] "GET /static/uploads/index.html HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:26:35] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:15] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:27:15] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:15] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:27:15] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:15] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:18] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:27:18] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:18] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:27:18] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:18] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:54] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:27:54] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:27:54] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:27:54] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:27:54] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:28:34] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:28:34] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:28:34] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:34] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:34] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:40] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:28:40] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:28:40] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:40] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:40] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:50] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:28:50] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:28:50] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:50] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:50] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:28:55] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:28:55] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:29:03] "POST /post HTTP/1.1" 302 -
192.168.1.25 - - [27/Feb/2025 17:29:03] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:29:03] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 17:29:03] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:29:03] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 17:29:03] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 17:29:03] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:07:12] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:07:13] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:07:13] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:07:13] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:07:13] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:07:13] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:09:25] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:09:25] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:09:25] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:09:25] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:09:25] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:09:25] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:09:30] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:09:30] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:09:30] "GET /favicon.ico HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:36] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:10:36] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:10:36] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:36] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:36] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:10:36] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:38] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:10:38] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:10:38] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:38] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:38] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:38] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:10:39] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:10:39] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:10:40] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:40] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:40] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:10:40] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:13:59] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:13:59] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "POST /post HTTP/1.1" 302 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 304 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:14:05] "GET /static/uploads/items_12.svg HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:14:21] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:14:21] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:14:21] "GET /static/uploads/a16ed6ce0abaadc59805e7df2095745f.jpg HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:14:22] "GET /static/uploads/Screenshot_20250227_162418.png HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:14:22] "GET /static/uploads/items_12.svg HTTP/1.1" 200 -
192.168.1.25 - - [27/Feb/2025 19:14:22] "GET /static/uploads/index.html HTTP/1.1" 404 -
192.168.1.25 - - [27/Feb/2025 19:14:22] "GET /static/uploads/avatar_1735322635977.png HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/gianni/vanano/app.py", line 1, in <module>
    from flask import Flask, render_template, request, redirect, url_for
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 35, in <module>
    from . import typing as ft
  File "/usr/lib/python3/dist-packages/flask/typing.py", line 53, in <module>
    BeforeRequestCallable = t.Union[
                            ^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 341, in inner
    return cached(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 463, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 671, in Union
    parameters = _remove_dups_flatten(parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 311, in _remove_dups_flatten
    params.append(p)
KeyboardInterrupt
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Traceback (most recent call last):
  File "/home/gianni/vanano/app.py", line 32, in <module>
    app.run(debug=True)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1059, in run_simple
    application = DebuggedApplication(application, evalex=use_evalex)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/debug/__init__.py", line 291, in __init__
    _log("warning", " * Debugger is active!")
  File "/usr/lib/python3/dist-packages/werkzeug/_internal.py", line 222, in _log
    _logger.addHandler(_ColorStreamHandler())
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/_internal.py", line 196, in __init__
    import colorama
  File "/usr/lib/python3/dist-packages/colorama/__init__.py", line 2, in <module>
    from .initialise import init, deinit, reinit, colorama_text, just_fix_windows_console
  File "/usr/lib/python3/dist-packages/colorama/initialise.py", line 6, in <module>
    from .ansitowin32 import AnsiToWin32
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 6, in <module>
    from .ansi import AnsiFore, AnsiBack, AnsiStyle, Style, BEL
  File "/usr/lib/python3/dist-packages/colorama/ansi.py", line 100, in <module>
    Back   = AnsiBack()
             ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/colorama/ansi.py", line 31, in __init__
    if not name.startswith('_'):
           ^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5050
 * Running on http://192.168.1.34:5050
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 929-414-535
192.168.1.25 - - [28/Feb/2025 09:12:54] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:12:54] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:13:14] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:13:14] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:13:16] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:13:16] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:14:13] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:14:14] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:38:49] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:38:49] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:38:52] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:38:52] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:38:52] "GET /favicon.ico HTTP/1.1" 404 -
192.168.1.25 - - [28/Feb/2025 09:39:02] "POST /post HTTP/1.1" 302 -
192.168.1.25 - - [28/Feb/2025 09:39:02] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:39:02] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:39:02] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:39:31] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:39:31] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:39:31] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:39:36] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:39:36] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:39:36] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:43:33] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:43:33] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:43:33] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:44:14] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:44:14] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:44:14] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:47:19] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:53:11] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 09:53:11] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 09:53:11] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:00:28] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:00:29] "GET /static/css/styles.css HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:00:29] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:00:32] "GET /post HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:00:33] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:00:43] "POST /post HTTP/1.1" 302 -
192.168.1.25 - - [28/Feb/2025 10:00:43] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:00:43] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:00:43] "GET /static/uploads/Screenshot_20250130_191128-modified.png HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:00:43] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:01:32] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:01:33] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:01:33] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:01:33] "GET /static/uploads/Screenshot_20250130_191128-modified.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:27:09] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:27:09] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:27:09] "GET /static/uploads/Screenshot_20250130_191128-modified.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:27:09] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:50:11] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:50:11] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:50:11] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:50:11] "GET /static/uploads/Screenshot_20250130_191128-modified.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:50:12] "GET / HTTP/1.1" 200 -
192.168.1.25 - - [28/Feb/2025 10:50:12] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:50:12] "GET /static/uploads/Screenshot_20250228_083144.png HTTP/1.1" 304 -
192.168.1.25 - - [28/Feb/2025 10:50:12] "GET /static/uploads/Screenshot_20250130_191128-modified.png HTTP/1.1" 304 -
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:445
 * Running on http://192.168.1.39:445
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 18:38:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:39:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:39:21] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Apr/2025 18:47:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:47:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:48:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:53:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:53:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:54:03] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:54:14] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 18:54:14] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 18:58:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:58:08] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:58:19] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 18:58:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 18:58:29] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 18:58:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:02:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:02:35] "GET /static/css/styles.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:02:47] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:02:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:02:50] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:02:51] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 19:04:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:06:41] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:06:47] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 19:12:51] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:12:51] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:12:54] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:00] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:13:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:00] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:13:00] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:02] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:05] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:13:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:16] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:34] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:13:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:48] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:13:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:13:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:14:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:14:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:15:42] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 19:18:41] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:18:41] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:18:47] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 34, in login
    pseudo = request.form['pseudo']
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'pseudo'
127.0.0.1 - - [17/Apr/2025 19:18:48] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:18:48] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:18:48] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:19:05] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:19:05] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:19:25] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:19:29] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:19:30] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:19:33] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 34, in login
    pseudo = request.form['pseudo']
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'pseudo'
127.0.0.1 - - [17/Apr/2025 19:19:33] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Apr/2025 19:19:33] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [17/Apr/2025 19:19:49] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:19:49] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 19:23:49] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:23:49] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:07] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:10] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:11] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:13] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:14] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:24:14] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:16] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:20] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:24:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:29] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:24:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:24:33] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:28:16] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:28:16] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:28:18] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:28:21] "GET /explore HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 19:28:22] "GET /explore HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 19:28:23] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:28:23] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:28:34] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:28:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:29:37] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 19:34:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:34:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:35:02] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:35:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:35:16] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:20] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:38:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:22] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:26] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:29] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:38:29] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:30] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:34] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:38:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:36] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:40] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:38:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:38:44] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:38:45] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 19:41:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:09] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:41:09] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:25] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:26] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:28] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:43] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:41:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:45] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:41:46] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:41:48] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:41:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:42:07] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:42:10] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:42:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:42:14] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:42:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:42:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:42:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:43:11] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:43:11] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:43:12] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 19:43:27] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:43:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:43:27] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Apr/2025 19:43:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:43:54] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:43:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:44:00] "POST /comment/0 HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:44:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:47:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:50:16] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [17/Apr/2025 19:51:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:51:13] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:51:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:51:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:51:36] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:54:29] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:54:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:56:37] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:56:37] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:56:38] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 19:57:14] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:57:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:57:15] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Apr/2025 19:58:08] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:58:15] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:58:19] "GET /post HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 19:58:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 19:58:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:01:05] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 20:01:05] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:01:05] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 20:01:09] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 20:01:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:01:10] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Apr/2025 20:47:24] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 20:47:24] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:47:25] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 20:47:38] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 20:47:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:47:38] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Apr/2025 20:48:13] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:48:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:48:44] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 20:48:44] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 20:48:51] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 21:49:09] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 21:49:09] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 21:49:09] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 21:49:13] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [17/Apr/2025 21:49:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 21:49:14] "GET /static/css/styles.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2025 23:35:41] "GET /explore HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2025 23:35:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 09:23:12] "GET /robots.txt HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 09:23:13] "GET /post HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 09:23:17] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:00:54] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 10:00:54] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:06:03] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 10:06:03] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:06:03] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 10:06:28] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:06:30] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:06:36] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 10:06:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:06:36] "GET /static/css/styles.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:16:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:16:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:22:29] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 10:22:29] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 10:22:30] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:22:30] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 10:25:52] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 10:58:31] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 11:28:51] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 11:28:51] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 11:59:00] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 11:59:00] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 11:59:01] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 11:59:04] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 11:59:26] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 11:59:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 11:59:26] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [18/Apr/2025 11:59:58] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 12:00:01] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 12:00:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:07:28] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:07:29] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:24:13] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:24:13] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:24:13] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2025 20:24:19] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:24:41] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:24:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:24:41] "GET /static/css/styles.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:25:12] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [18/Apr/2025 20:25:34] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [18/Apr/2025 20:28:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:28:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:29:05] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [18/Apr/2025 20:29:26] "POST / HTTP/1.1" 405 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [18/Apr/2025 20:39:34] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [18/Apr/2025 20:39:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:40:08] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:40:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:40:27] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:40:28] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [18/Apr/2025 20:43:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:47:36] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [18/Apr/2025 20:51:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:52:10] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [18/Apr/2025 20:56:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:56:36] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:56:36] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:56:55] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:56:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:57:12] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:57:12] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 20:59:42] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [18/Apr/2025 20:59:42] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [18/Apr/2025 21:09:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 21:09:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 21:09:36] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2025 21:09:43] "GET /search?q=uwu HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:35:43] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 09:35:44] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:35:44] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 09:35:59] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 09:35:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:35:59] "GET /static/css/styles.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:36:04] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:36:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:36:11] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:36:26] "GET /search?q=Tiago HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:36:37] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:36:44] "GET /search?q=Thiago HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 09:36:57] "GET /search?q=Proton HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:06:06] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:06:09] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:06:10] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 10:06:16] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:06:16] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:06:21] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:06:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:06:21] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:06:27] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:06:32] "GET /search?q=uwu HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
127.0.0.1 - - [19/Apr/2025 10:18:19] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:18:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:18:19] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:21:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:21:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:22:52] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:22:59] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:23:00] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 484-425-918
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
  File "/home/gianni/Pynia/app.py", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
 * Serving Flask app 'app'
 * Debug mode: on
Permission denied
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:445
 * Running on http://192.168.1.39:445
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-589-838
127.0.0.1 - - [19/Apr/2025 10:42:49] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 87, in index
    posts = get_posts()
            ^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 59, in get_posts
    c.execute("SELECT profile_picture FROM users WHERE username = ?", (post[1],))
sqlite3.OperationalError: no such column: profile_picture
127.0.0.1 - - [19/Apr/2025 10:42:49] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:42:49] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:42:50] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:44:33] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 87, in index
    posts = get_posts()
            ^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 59, in get_posts
    c.execute("SELECT profile_picture FROM users WHERE username = ?", (post[1],))
sqlite3.OperationalError: no such column: profile_picture
127.0.0.1 - - [19/Apr/2025 10:44:33] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:44:33] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:44:33] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:45:03] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 87, in index
    posts = get_posts()
            ^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 59, in get_posts
    c.execute("SELECT profile_picture FROM users WHERE username = ?", (post[1],))
sqlite3.OperationalError: no such column: profile_picture
127.0.0.1 - - [19/Apr/2025 10:45:04] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:45:04] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:45:04] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-589-838
127.0.0.1 - - [19/Apr/2025 10:47:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:47:19] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:47:19] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:47:39] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:47:41] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:47:54] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:47:55] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:48:13] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:48:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:48:26] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:49:57] "POST /modifier-profil HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:49:57] "GET /profil/Starkot48 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 221, in view_profile
    return render_template('profile.html', user=user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: profile.html
127.0.0.1 - - [19/Apr/2025 10:49:58] "GET /profil/Starkot48?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:49:58] "GET /profil/Starkot48?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:49:58] "GET /profil/Starkot48?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-589-838
127.0.0.1 - - [19/Apr/2025 10:52:36] "GET /profil/Starkot48 HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 10:52:37] "GET /profil/Starkot48 HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 10:52:46] "POST /modifier-profil HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 238, in edit_profile
    filename = user[2]
               ^^^^^^^
TypeError: 'NoneType' object is not subscriptable
127.0.0.1 - - [19/Apr/2025 10:52:46] "GET /modifier-profil?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:52:46] "GET /modifier-profil?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:52:47] "GET /modifier-profil?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:52:51] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:52:55] "POST /modifier-profil HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 238, in edit_profile
    filename = user[2]
               ^^^^^^^
TypeError: 'NoneType' object is not subscriptable
127.0.0.1 - - [19/Apr/2025 10:52:55] "GET /modifier-profil?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:52:55] "GET /modifier-profil?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:53:09] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:53:22] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:53:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:53:22] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 10:53:41] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:53:43] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:53:43] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:54:19] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:54:23] "POST /modifier-profil HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 238, in edit_profile
    filename = user[2]
               ^^^^^^^
TypeError: 'NoneType' object is not subscriptable
127.0.0.1 - - [19/Apr/2025 10:54:23] "GET /modifier-profil?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:54:23] "GET /modifier-profil?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-589-838
127.0.0.1 - - [19/Apr/2025 10:56:51] "POST /modifier-profil HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 10:56:56] "GET /modifier-profil HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 10:57:00] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:57:03] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:57:17] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:57:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:57:36] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:57:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:57:58] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:58:14] "POST /modifier-profil HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 10:58:14] "GET /profil/Starkot48 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 221, in view_profile
    return render_template('profile.html', user=user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: profile.html
127.0.0.1 - - [19/Apr/2025 10:58:14] "GET /profil/Starkot48?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:58:14] "GET /profil/Starkot48?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:58:14] "GET /profil/Starkot48?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 10:59:50] "GET /profil/Starkot48 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 10:59:51] "GET /static/default.png HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 11:00:07] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:00:24] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:00:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:00:28] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:00:30] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:00:49] "POST /modifier-profil HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:00:49] "GET /profil/Starkot48 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:01:02] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:01:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:01:11] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 11:01:19] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:01:21] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 11:01:42] "POST /modifier-profil HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:01:44] "GET /profil/Starkot48 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:01:54] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:02:12] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:02:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:02:16] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:02:22] "GET /search?q=uwu HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:02:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:02:51] "GET /modifier-profil HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 11:02:58] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:03:00] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:03:10] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:03:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:03:14] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:03:33] "POST /modifier-profil HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:03:34] "GET /profil/uwu HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:03:36] "GET /static/default.png HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 11:09:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:09:19] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:09:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:09:46] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:09:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:15:39] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 118-589-838
127.0.0.1 - - [19/Apr/2025 11:29:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:29:29] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 11:29:34] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:29:34] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 11:29:52] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 11:29:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:29:53] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 11:29:53] "GET /static/uploads/logo.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:30:14] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 11:35:50] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 125, in index
    return render_template('index.html', posts=posts, username=session['username'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/index.html", line 217, in top-level template code
    <a href="{{ url_for('rec_page') }}" style="position: fixed; bottom: 20px; left: 20px; z-index: 100;">
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'rec_page'. Did you mean 'register' instead?
127.0.0.1 - - [19/Apr/2025 11:35:50] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 11:35:50] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 11:35:51] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:445
 * Running on http://192.168.1.39:445
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 702-873-382
127.0.0.1 - - [19/Apr/2025 19:23:36] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:23:40] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:23:42] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:23:46] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 19:23:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:23:46] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 19:23:49] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 261, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [19/Apr/2025 19:23:50] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:23:50] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:23:51] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:36:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:37:07] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:37:08] "GET /static/style.css HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 19:37:11] "GET /search?q=uwu HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:37:13] "GET /profil/uwu HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:37:14] "GET /static/default.png HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 19:38:14] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 261, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [19/Apr/2025 19:38:15] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 19:38:15] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Apr/2025 19:38:15] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:39:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:39:14] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:39:20] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 19:39:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:39:20] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 19:39:26] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:39:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:39:38] "GET /profil/uwu HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 19:39:45] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 22:03:19] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 22:03:19] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Apr/2025 22:03:20] "GET /getcmd HTTP/1.1" 404 -
127.0.0.1 - - [19/Apr/2025 22:03:21] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2025 22:03:21] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 05:53:21] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 09:24:10] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 09:24:10] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 09:24:10] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 09:54:25] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 09:54:25] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 09:54:25] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 09:54:30] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 09:54:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 09:54:31] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Apr/2025 09:54:31] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 10:40:22] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 10:40:22] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:40:22] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 10:40:41] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:40:47] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:40:56] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:40:58] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:41:19] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 10:41:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:41:19] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Apr/2025 10:41:19] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 10:41:32] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:41:36] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 261, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [20/Apr/2025 10:41:36] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:41:36] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:41:37] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:43:40] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:43:41] "GET /static/style.css HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 10:43:50] "GET /search?q=Starkot48 HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:43:53] "GET /profil/Starkot48 HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:43:53] "GET /static/default.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 10:44:01] "GET /modifier-profil HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:44:58] "POST /modifier-profil HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 10:44:58] "GET /profil/Starkot48 HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:45:05] "GET /profil/Starkot48 HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 10:45:14] "POST /modifier-profil HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 10:45:14] "GET /profil/Starkot48 HTTP/1.1" 200 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 702-873-382
127.0.0.1 - - [20/Apr/2025 11:11:39] "GET /profil/Starkot48 HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 11:11:41] "GET /modifier-profil HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 11:11:59] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 144, in index
    return render_template('index.html', posts=posts, username=session['username'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/index.html", line 206, in top-level template code
    <textarea name="bio" id="bio" rows="4" style="width: 100%; margin-bottom: 10px;">{{ current_user.bio }}</textarea><br>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'current_user' is undefined
127.0.0.1 - - [20/Apr/2025 11:11:59] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 11:11:59] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 11:12:00] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 11:12:47] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 144, in index
    return render_template('index.html', posts=posts, username=session['username'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/index.html", line 206, in top-level template code
    <textarea name="bio" id="bio" rows="4" style="width: 100%; margin-bottom: 10px;">{{ current_user.bio }}</textarea><br>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'current_user' is undefined
127.0.0.1 - - [20/Apr/2025 11:12:47] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [20/Apr/2025 11:12:47] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
 * Detected change in '/home/gianni/Pynia/app.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/gianni/Pynia/app.py", line 8, in <module>
    from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required as flask_login_required, current_user
ModuleNotFoundError: No module named 'flask_login'
Traceback (most recent call last):
  File "/home/gianni/Pynia/app.py", line 8, in <module>
    from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required as flask_login_required, current_user
ModuleNotFoundError: No module named 'flask_login'
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8090
 * Running on http://192.168.1.39:8090
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 129-201-343
127.0.0.1 - - [20/Apr/2025 18:54:54] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 18:54:54] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 18:54:54] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 18:54:58] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 18:55:05] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 18:55:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 18:55:05] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Apr/2025 18:55:09] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [20/Apr/2025 18:55:10] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 18:55:10] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 18:55:10] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 19:32:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 19:32:44] "POST /modify_account HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 19:32:44] "GET /profil/uwu HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 19:32:44] "GET /static/default_profile.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 20:15:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:15:14] "POST /modify_account HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 20:15:14] "GET /profil/uwu HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:15:14] "GET /static/default_profile.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 20:15:35] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 20:15:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:15:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:15:47] "GET /post HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:15:50] "POST /post HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 20:15:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:15:51] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 20:15:59] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:16:01] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 20:16:05] "GET /profil/DELETE%20*%20FROM%20DATA_BASE; HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:13:39] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 21:13:56] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 21:13:56] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:14:05] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:14:17] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 21:14:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:14:17] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [20/Apr/2025 21:14:18] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 21:49:42] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 21:49:43] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:49:43] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 21:52:01] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 21:52:01] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:52:11] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 21:52:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:52:44] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [20/Apr/2025 21:52:46] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:52:46] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:52:49] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:52:53] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:52:54] "GET /static/style.css HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 21:52:59] "GET /search?q=uwu HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:53:01] "GET /profil/uwu HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 21:53:01] "GET /static/default_profile.png HTTP/1.1" 404 -
127.0.0.1 - - [20/Apr/2025 22:32:00] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [20/Apr/2025 22:32:00] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2025 22:32:00] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 09:28:36] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 09:28:36] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 09:28:36] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 09:28:40] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 09:28:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 09:28:40] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 09:28:41] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 09:28:53] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 09:28:58] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 09:28:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 09:29:09] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 09:29:09] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 09:29:09] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 09:29:10] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 10:54:26] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 10:54:30] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 10:55:01] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 10:55:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 10:55:03] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 10:55:03] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 11:38:45] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 11:38:45] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:00] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 18:18:00] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:00] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 18:18:04] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:09] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 18:18:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:09] "GET /static/css/styles.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:09] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 18:18:18] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:21] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 18:18:21] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:21] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:22] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:28] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 18:18:28] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 18:18:28] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 18:18:58] "POST /modify_account HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 18:18:58] "GET /profil/admin HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:18:58] "GET /static/default_profile.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 18:19:00] "GET /profil/admin HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:14] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:19] "POST /modify_account HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 18:19:19] "GET /profil/admin HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:20] "GET /profil/admin HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:28] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:28] "GET /static/style.css HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 18:19:32] "GET /search?q=+ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:19:33] "GET /profil/DELETE%20*%20FROM%20DATA_BASE; HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 18:26:59] "GET /robots.txt HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 18:27:00] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:04:17] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:04:17] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:04:18] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:04:23] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:04:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:04:23] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 19:04:23] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:05:30] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 19:05:30] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:05:30] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:05:31] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:02] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:09] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:18] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:22] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:22] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:23] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
127.0.0.1 - - [21/Apr/2025 19:06:30] "Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
POST /api/comment/1 HTTP/1.1" 500 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
127.0.0.1 - - [21/Apr/2025 19:06:30] "Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
POST /api/comment/1 HTTP/1.1" 500 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
127.0.0.1 - - [21/Apr/2025 19:06:30] "Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
POST /api/comment/1 HTTP/1.1" 500 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 237, in api_add_comment
    if not current_user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/gianni/venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 73, in load_user
    c.execute("SELECT id, username FROM users WHERE id = ?", (user_id,))
sqlite3.OperationalError: database is locked
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:06:30] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:07:41] "POST /api/comment/1 HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:07:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:07:47] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:07:59] "POST /modify_account HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:07:59] "GET /profil/uwu HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:08:00] "GET /static/default_profile.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:08:20] "GET /profil/DELETE%20*%20FROM%20DATA_BASE; HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:08:25] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:08:29] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:08:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:48:47] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:48:49] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:48:50] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:48:56] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:49:02] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:49:03] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:49:11] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:49:20] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:49:27] "POST /login HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:49:45] "POST /register HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:49:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:49:46] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 19:49:46] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:49:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:15] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 19:50:16] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 19:50:17] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 19:50:19] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:19] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:21] "GET /rec?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:32] "POST /modify_account HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:50:32] "GET /profil/Thiago HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:32] "GET /static/default_profile.png HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:50:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:43] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:52] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [21/Apr/2025 19:50:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:57] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:50:57] "GET /static/style.css HTTP/1.1" 404 -
127.0.0.1 - - [21/Apr/2025 19:51:04] "GET /search HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 19:51:07] "GET /rec HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/Pynia/app.py", line 317, in rec_page
    return render_template('rec.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/gianni/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/gianni/Pynia/templates/rec.html", line 10, in top-level template code
    <a href="{{ url_for('home') }}" style="color: #1e90ff;">← Retour à l'accueil</a>
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gianni/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'home'. Did you mean 'api_add_comment' instead?
127.0.0.1 - - [21/Apr/2025 19:51:08] "GET /rec?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 19:51:08] "GET /rec?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [21/Apr/2025 21:02:33] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2025 23:13:54] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [22/Apr/2025 09:39:28] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [22/Apr/2025 09:39:36] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Apr/2025 09:39:36] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [22/Apr/2025 09:40:03] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [22/Apr/2025 09:40:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Apr/2025 09:40:15] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [22/Apr/2025 09:40:15] "GET /static/profile_pics/default.png HTTP/1.1" 404 -
